FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY ["NeuralNetAsp.csproj", "."]
WORKDIR /app
RUN pwd
RUN ls -a
WORKDIR /app
RUN dotnet restore "./NeuralNetAsp.csproj"
WORKDIR /app
COPY . .
WORKDIR /app
RUN dotnet build "NeuralNetAsp.csproj" -c Release -o /app/build
FROM build AS publish
WORKDIR /app
RUN dotnet publish "NeuralNetAsp.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NeuralNetAsp.dll"]

